### ISSUE TITLE
company-tern Request Failed: ((wrong-type-argument processp nil))

### ISSUE THREAD

**Issue by thepreacher** [proofit404/company-tern#15]
I've been batling this for a couple of days now. In any javascript file when I start typing and autocompletion tries to start, I ge the above error. I have tried starting emac in debug mode but the error message is the same. I find no clue in the error as to where to even beging looking. Anyway by commenting our the code and restarting emacs many times. I narrowed it down to company-tern. Because, if I don't load it I get some sort of completion from Tern alone. However if I enable it the error comes back. When I do ```C-h m```, company is listed as a minor mode but company-tern is not listed. Below are the code so far for my Javascript and Company-tern setups:

javascript.el
```
(use-package json-mode)

(use-package js2-mode
  :init (add-to-list 'auto-mode-alist '("\\.js\\'" . js2-mode))
  :config
    (use-package tern
      :commands tern-mode
      :init
      (add-hook 'js2-mode-hook 'tern-mode)
      (add-hook 'jsx-mode-hook 'tern-mode)
      :config
      (progn
        (use-package company-tern
         :init
         (add-to-list 'company-backends 'company-tern))
         (define-key tern-mode-keymap (kbd "M-.") 'tern-find-definition)
         (define-key tern-mode-keymap (kbd "C-M-.") 'tern-find-definition-by-name)
         (define-key tern-mode-keymap (kbd "M-,") 'tern-pop-find-definition)
         (define-key tern-mode-keymap (kbd "C-c C-r") 'tern-rename-variable)
         (define-key tern-mode-keymap (kbd "C-c C-c") 'tern-get-type)
         (define-key tern-mode-keymap (kbd "C-c C-d") 'tern-get-docs)
         (define-key tern-mode-keymap (kbd "M-<return>") 'tern-get-docs))))
```
company.el
```
(use-package company
  ;:diminish company-mode
  :config
  (add-hook 'after-init-hook 'global-company-mode))
```
In my init.el file, I load ```company.el``` before ```javascript.el```. I have also globally installed tern with ```npm install -g tern```

**Comment by proofit404** [comment]
Maybe `M-: (company-tern) RET` can provide useful stack trace.

**Comment by thepreacher** [comment]
Thanks for your response. So I did ```M-: (company-tern) RET``` as suggested and the following is what I got. Pardon me but i don't understand emacs-lisp so I can't quite understand it all:
```
Debugger entered--Lisp error: (wrong-number-of-arguments (1 . 2) 0)
  company-tern()
  eval((company-tern) nil)
  eval-expression((company-tern) nil)
  #<subr call-interactively>(eval-expression nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> eval-expression nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (eval-expression nil nil))
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

**Comment by proofit404** [comment]
I'm sorry. There was a mistake in my snippet. Can you eval `(company-tern 'interactive)`?

**Comment by thepreacher** [comment]
Ok so this is what I got this time:
```
Debugger entered--Lisp error: (error "Company: backend company-tern async timeout with args (candidates )")
  signal(error ("Company: backend company-tern async timeout with args (candidates )"))
  error("Company: backend %s async timeout with args %s" company-tern (candidates ""))
  company--force-sync(company-call-backend-raw (candidates "") company-tern)
  company-call-backend(candidates "")
  company--fetch-candidates("")
  company-calculate-candidates("")
  #[0 "\n\203	\nC\202\n\211\205\233\211@\3009\204\306!\203<9\2036\307N\310=\2046\307N?\205@\311!\205@\312!\202@\313\312\"\240\210\300\242\203\224\314\300\242!\203\216\315\300\242!\211\301\316\f!\240\210\301\242:\204w
\203i\317\320!\210\301\242\310=\203\216\321\322!\210\202\216
\203\300\242\323\301\242!\210\324\325\326 \"\210\327\330!\210\331\332\301\242\"\210A\266\202\202\n\207" [("") (nil) company-backend company-backends company-prefix company--manual-action functionp company-init t company-init-backend prefix company--multi-backend-adapter company--good-prefix-p company--prefix-str company-calculate-candidates message "No completion found" company-cancel unique company-update-candidates run-hook-with-args company-completion-started-hook company-explicit-action-p company-call-frontends show throw --cl-block-nil-- company--manual-prefix] 6 "\n\n(fn)"]()
  funcall(#[0 "\n\203	\nC\202\n\211\205\233\211@\3009\204\306!\203<9\2036\307N\310=\2046\307N?\205@\311!\205@\312!\202@\313\312\"\240\210\300\242\203\224\314\300\242!\203\216\315\300\242!\211\301\316\f!\240\210\301\242:\204w
\203i\317\320!\210\301\242\310=\203\216\321\322!\210\202\216
\203\300\242\323\301\242!\210\324\325\326 \"\210\327\330!\210\331\332\301\242\"\210A\266\202\202\n\207" [("") (nil) company-backend company-backends company-prefix company--manual-action functionp company-init t company-init-backend prefix company--multi-backend-adapter company--good-prefix-p company--prefix-str company-calculate-candidates message "No completion found" company-cancel unique company-update-candidates run-hook-with-args company-completion-started-hook company-explicit-action-p company-call-frontends show throw --cl-block-nil-- company--manual-prefix] 6 "\n\n(fn)"])
  company--begin-new()
  company--perform()
  #[0 "\301 \210\207" [company-candidates company--perform] 1 "\n\n(fn)"]()
  funcall(#[0 "\301 \210\207" [company-candidates company--perform] 1 "\n\n(fn)"])
  company-auto-begin()
  company-manual-begin()
  company-begin-backend(company-tern)
  company-tern(interactive)
  eval((company-tern (quote interactive)) nil)
  eval-expression((company-tern (quote interactive)) nil)
  #<subr call-interactively>(eval-expression nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> eval-expression nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (eval-expression nil nil))
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```
Thanks for taking the time to help.

**Comment by proofit404** [comment]
Maybe removing `elc` byte code files from company-tern and company packages will clarify this stack trace.

**Comment by thepreacher** [comment]
Sorry about the late reply. In the mean time I managed to find a dotemacs that used company and tern like I wanted to. I intend to use and study the dotemacs to implement my own. I don't understand most of it at the moment however. The general vibe I'm getting from IRC is that it could be any number is things that cause such an error or something and since others are successfully using company-tern, I'm inclined to agree. I'll create a new issue if I get this problem again in the future. Thanks again.

**Comment by proofit404** [comment]
Also feel free to reopen this issue with more verbose stack trace.

Have a good day.

**Comment by josephskrzysowski** [comment]
Hey @proofit404 , as it so happens, I am having this issue and have boiled it down to company-tern. I can provide info but first here's how I got here; I am not that experienced with emacs-lisp but I have spent lots of time duct-taping my config together. I am using a combo of these two [configs{](https://github.com/phardyn/emacs/blob/master/README.md) and [}](https://github.com/foretagsplatsen/emacs-js) along with some keybindings and some small things. I could provide info that is needed, just tell me what you need.  Now, autocomplete works in js2-jsx-mode but I get these errors when I enable rjsx-mode and autocomplete does not work: 

```
Invalid face reference: t [564 times]
Request failed: ((args-out-of-range [cl-struct-url http nil nil 127.0.0.1 46487 / nil nil nil nil t] 12))
Company: An error occurred in auto-begin
Company: backend company-tern async timeout with args (candidates onVide)
Invalid face reference: t [48 times]
```
(Is this hijacking a dead thread? Should I open a new issue or could we reopen this? Any advice or direction will be greatly appreciated as I think this will be a big learning experience with me finally fixing this issue) Thanks in advance and I will respond with any info needed pretty quick.

**Comment by josephskrzysowski** [comment]
```Invalid face reference: t [564 times]Request failed: ((args-out-of-range [cl-struct-url http nil nil 127.0.0.1 46487 / nil nil nil nil t] 12))Company: An error occurred in auto-beginCompany: backend company-tern async timeout with args (candidates onVide)Invalid face reference: t [48 times]```
