### ISSUE TITLE
Incomplete completion

### ISSUE THREAD

**Issue by JesusMtnez** [proofit404/company-tern#16]
I'm using `tern` with `tern-node-express` to get Express autocompletion.

My `.tern-project` is:
```json
{
  "plugins": {
    "node": {},
    "node-express": {}
  }
}
```

But when I try to auto complete the express app, it gives an incomplete auto completion

![screen shot 2015-11-28 at 20 49 12](https://cloud.githubusercontent.com/assets/8639179/11453617/091040b2-9612-11e5-9c80-37bd4f6641b1.png)

My company configuration:
```elisp
;; Company
(use-package company
  :ensure t
  :config (progn (add-hook 'after-init-hook 'global-company-mode)
                 (setq company-idle-delay 0.1)          ; Reduce company auto complete start time
                 (setq company-minimum-prefix-length 1) ; Reduce prefix to start completion
                 (setq company-show-numbers t)         ; Show number to quick access with M-number
                 (add-to-list 'company-backends 'company-tern))
  :diminish company-mode)
```

**Comment by proofit404** [comment]
Does `*Completions*` buffer triggered with `C-M-i` contains different candidates list?

**Comment by JesusMtnez** [comment]
No, this is the result:
![screen shot 2015-11-28 at 21 12 22](https://cloud.githubusercontent.com/assets/8639179/11453687/be43d942-9614-11e5-9a6c-95d02257da4b.png)

**Comment by proofit404** [comment]
I think this is tern problem because `company-tern` provide plain candidates from `tern`

**Comment by JesusMtnez** [comment]
So, is there a way to solve it?

**Comment by proofit404** [comment]
Open issue on tern bug tracker. I can help you, sorry.
