### ISSUE TITLE
Make company-tern support company-quickhelp?

### ISSUE THREAD

**Issue by galeo** [proofit404/company-tern#17]
Could company-tern support [company-quickhelp](https://github.com/expez/company-quickhelp) to show documentation popups?

**Comment by proofit404** [comment]
Yes, it works with quickhelp mode. I have check this.

**Comment by galeo** [comment]
Sorry, but I seem to have encountered a problem. I bind **company-jquery** to work with **company-tern**, when I typed this code:
```js
<script>
  $('#search-button').click(function (e) {
    e.prevent⌷  // ⌷ is the cursor, try to type 'e.preventDefault()', but only one candidate 'Extensions'
  })
</script>
```

The error occurred:
```
Error running timer ‘company-quickhelp--show’: (error "Company: backend (company-tern :with company-jquery) error \"Buffer is read-only: #<buffer *company-documentation*>\" with args (doc-buffer preventExtensions)")
```

**Comment by proofit404** [comment]
This happens because of [this line in the jquery-doc package](https://github.com/ananthakumaran/jquery-doc.el/blob/7836ba986dd7317f68f07520445bd2260154c283/jquery-doc.el#L344).

**Comment by galeo** [comment]
Thanks. Could we just delete the code `(help-mode)` in this line? Or if there is a better method to fix this?

**Comment by proofit404** [comment]
I have no idea, since this isn't my package :) Ask this question in the project related bug tracker.

**Comment by galeo** [comment]
Thank you for your help. I have submitted an issue to [jquery-doc](https://github.com/ananthakumaran/jquery-doc.el).

**Comment by proofit404** [comment]
You're welcome ;)
