### ISSUE TITLE
Stable release doesn't work

### ISSUE THREAD

**Issue by favadi** [proofit404/company-tern#23]
The current version in melpa-stable is broken. The problem is https://github.com/company-mode/company-mode/issues/441. It is already fixed in https://github.com/proofit404/company-tern/commit/0c5fa13381915d21b62a70818d25901efb0f4a05. Can you tag a release to fix the melpa-stable release?

**Comment by DamienCassou** [comment]
I have the same problem. A new release would be nice.

**Comment by proofit404** [comment]
Done. I'm sorry, I completely forget about this issue.
