### ISSUE TITLE
[Feature request] Follow definitions in files loaded via requires

### ISSUE THREAD

**Issue by fusion809** [proofit404/company-tern#27]
Hi,

I have scripts that have requires lines in them and definitions in these required files are not taken into consideration in this package's auto-completions. For example, git clone my [JScripts repo](https://github.com/fusion809/JScripts) and open math/RK4/airy.js in Emacs with this plugin installed and you'll see that the `getX` doesn't get suggested as a completion as you're trying FUNCT.RK4.getX in it. Even though getX is defined elsewhere. 

Thanks for your time,
Brenton

**Comment by proofit404** [comment]
Hi!

Since company-tern is just a UI backend above tern package, you should try to setup tern project properly. I suggest reporting this question its bug tracker or mailing list.

Hope this helps.

Regards, Artem.
