### ISSUE TITLE
feature suggestion.

### ISSUE THREAD

**Issue by Yeonjj** [proofit404/company-tern#29]
Hi, 

First, I'd like to thank you for this awesome work!

I am a beginner of emacs so please understand me if I'm asking an absurdity. :)

So I was working on a simple js project and I got an error `Request failed : (nil)` But not on everywhere, only after the place where it has a wrong syntax. (e.g. inside of wrong syntax class. But weirdly it works before the class in the same file.) I guess it has something related to `tern`? 
I was focused only on why it gives me `Request failed : (nil)` and I didn't think that I got syntax error until I found it.

 I know it would be more detective if I just run it. But if it's about syntax problem related to `Request failed` error, then why doesn't it just give me a direct message of the syntax error in realtime? Is it out of a range of `company-tern` deals with?

I know `js2-mode` does this but I can't use this for my project.

**Comment by proofit404** [comment]
Hi, [tern.js was abandoned for a long time](https://github.com/ternjs/tern/commit/ae83725819286d3f134a6b9956f1117b341e1040#diff-04c6e90faac2675aa89e2176d2eec7d8). Looks like [things has changed recently](https://github.com/ternjs/tern/commit/c6639cb471aaa7f844b04dd96970be8522f21491#diff-04c6e90faac2675aa89e2176d2eec7d8).

I already moved my development to lsp using [eglot](https://github.com/joaotavora/eglot). I tried [lsp-mode](https://github.com/emacs-lsp/lsp-mode) as well. It also works fine.

**Comment by Yeonjj** [comment]
I’m so fall behind this :( The link you gave me is just what I wanted! Thank you!
